### PR TITLE
[ new ] grow

### PR DESCRIPTION
**Pull request by Matthew-Mosior**
This PR adds `grow` for `MArray`s, provided by @stefan-hoeck, which grows an `MArray` by the given number of elements.

### CODE REVIEW

**Comment by Matthew-Mosior** [comment]
@stefan-hoeck 

Not sure if there is a more efficient way to implement this, maybe using `unsafeCreate`?  I was having trouble getting it to compile though.

**Comment by Matthew-Mosior** [comment]
> @stefan-hoeck
> 
> Not sure if there is a more efficient way to implement this, maybe using `unsafeCreate`? I was having trouble getting it to compile with `unsafeCreate` unfortunately.

I've addressed this via f1c0a836743d272ea96671953ab3a57393754d89.

**Comment by Matthew-Mosior** [comment]
@stefan-hoeck 

I've converted this to draft, the implementations of `grow` here are very slow.  Would love if you had any ideas of how to implement this efficiently (maybe via a `%foreign`)?  Not sure.

**Comment by stefan-hoeck** [comment]
I should be able to find some time to look into this and your PR for containers tomorrow. Sorry, it's a busy time.

**Comment by Matthew-Mosior** [comment]
> @stefan-hoeck 
> 
> I've converted this to draft, the implementations of `grow` here are very slow.  Would love if you had any ideas of how to implement this efficiently (maybe via a `%foreign`)? Or maybe a `grow` on a `MArray` would be best performance-wise (have no idea how to implement this though).

@stefan-hoeck 

Actually, I think for maximum performance here, we'd definitely want `grow` on a `MArray`, again just have no idea how this would be implemented.

**Comment by stefan-hoeck** [comment]
Here's how to safely grow a mutable array:

```idris
parameters {0 rs : Resources}
           {n : Nat}
           (r : MArray n a)
           {auto 0 p : Res r rs}

  writeMArray :
       (k : Nat)
    -> {auto 0 lte : LTE k n}
    -> (tgt : MArray (m+n) a)
    -> F1' (tgt::rs)
  writeMArray 0     tgt t = () # t
  writeMArray (S k) tgt t =
    let v # t := getNat r k t
        _ # t := setNat tgt k {lt = ltAddLeft lte} v t
     in writeMArray k tgt t


  ||| Allocates a new mutable array and adds the elements from `r`
  ||| at its beginning.
  export
  mgrow : (m : Nat) -> (deflt : a) -> (1 t : T1 rs) -> A1 rs (MArray (m+n) a)
  mgrow m deflt t =
    let A tgt t := newMArray (m+n) deflt t
        _ #   t := writeMArray n tgt t
     in A tgt t

||| Utility for growing and replacing a single mutable array.
mgrow1 :
     {n : Nat}
  -> (r : MArray n a)
  -> (m : Nat)
  -> (deflt : a)
  -> (1 t : T1 [r])
  -> A1 [] (MArray (m+n) a)
mgrow1 r m dflt t =
  let A tgt t := mgrow r m dflt t
      _ #   t := release r t
   in A tgt t
```

Growing an immutable indexed array could be implemented in a similar fashion by allocating a new mutable array, writing its elements, and freezing it at the end. Growing an existential array (`Array`) should be implemented in terms of the indexed version.

The above requires the following proof to be added to `Data.Array.Index`:

```idris
export
0 ltAddLeft : LT k n -> LT k (m+n)
ltAddLeft {m = 0}   lt = lt
ltAddLeft {m = S x} lt = lteSuccRight $ ltAddLeft lt
```

**Comment by stefan-hoeck** [comment]
For performance reasons, we might want to add array copying as a primitive via the FFI. This should go to another PR, however. Also, after some discussions on discord, I'll look into making `R1` in idris2-ref1 a proper dependent type. Not sure how well that will work out but it might make resource juggling a bit more straight forward.

**Comment by Matthew-Mosior** [comment]
@stefan-hoeck 

Awesome, thank you for spending time to help with this!

I have added the `grow` implementations you've provided for `MArray` via ab669e3729696524c1688f9517f60470bd6b5037.

I've also removed the slow `grow` implementations I wrote for `Array/IArray` in ab669e3729696524c1688f9517f60470bd6b5037.

**Comment by stefan-hoeck** [comment]
Could you verify that my version shows decent performance? I haven't tested it.

**Comment by Matthew-Mosior** [comment]
> Could you verify that my version shows decent performance? I haven't tested it.

Yes I'll re-write the benchmark with it and report back here.

**Comment by Matthew-Mosior** [comment]
@stefan-hoeck 

I think the builds are now failing for some reason:

```
[ build ] Data.Array.Mutable:221:9--221:10
[ build ]  217 |         -> (deflt : a)
[ build ]  218 |         -> (1 t : T1 rs)
[ build ]  219 |         -> A1 rs (MArray (m+n) a)
[ build ]  220 |   mgrow m deflt t =
[ build ]  221 |     let A tgt t := newMArray (m+n) deflt t
[ build ]                ^
[ build ] 
[ build ] Error: While processing right hand side of mgrow1. Undefined name A. 
[ build ] 
[ build ] Data.Array.Mutable:235:7--235:8
[ build ]  231 |   -> (deflt : a)
[ build ]  232 |   -> (1 t : T1 [r])
[ build ]  233 |   -> A1 [] (MArray (m+n) a)
[ build ]  234 | mgrow1 r m dflt t =
[ build ]  235 |   let A tgt t := mgrow r m dflt t
[ build ]              ^
```

Maybe its because of the latest PR?

**Comment by Matthew-Mosior** [comment]
@stefan-hoeck 

Also seeing this now trying to build locally:

```
[ build ] 3/8: Building Data.Array.Mutable (src/Data/Array/Mutable.idr)
[ build ] Error: While processing right hand side of mgrow. When unifying:
[ build ]     a (implicitly bound at Data.Array.Mutable:221:9--221:10)
[ build ] and:
[ build ]     MArray (?m + n) a
[ build ] Mismatch between: a (implicitly bound at Data.Array.Mutable:221:9--221:10) and MArray' RPure (?m + n) a.
[ build ] 
[ build ] Data.Array.Mutable:222:34--222:37
[ build ]  218 |         -> (1 t : T1 rs)
[ build ]  219 |         -> A1 rs (MArray (m+n) a)
[ build ]  220 |   mgrow m deflt t =
[ build ]  221 |     let A tgt t := newMArray (m+n) deflt t
[ build ]  222 |         _ #   t := writeMArray n tgt t
[ build ]                                         ^^^
[ build ] 

```

**Comment by stefan-hoeck** [comment]
Yes, sorry, there has been a breaking chang in idris2-ref1. It should be enough to replace `A x t` with `x # t` for all `x` everywhere in the code I posted above. Data type `A1` and its constructor no longer exist.

**Comment by Matthew-Mosior** [comment]
Seems that this now gives:

```
[ build ] Error: While processing right hand side of mgrow. Ambiguous elaboration. Possible results:
[ build ]     ?postpone [no locals in scope]
[ build ]     ?postpone [no locals in scope]
[ build ]     ?postpone [no locals in scope]
[ build ] 
[ build ] Data.Array.Mutable:221:13--221:14
[ build ]  217 |         -> (deflt : a)
[ build ]  218 |         -> (1 t : T1 rs)
[ build ]  219 |         -> A1 rs (MArray (m+n) a)
[ build ]  220 |   mgrow m deflt t =
[ build ]  221 |     let tgt # t := newMArray (m+n) deflt t
[ build ]                    ^
[ build ] 
[ build ] Error: While processing right hand side of mgrow1. Sorry, I can't find any elaboration which works. All errors:
[ build ] If Data.Linear.Token.(#): When unifying:
[ build ]     R1 ?rs ?a
[ build ] and:
[ build ]     A1 ?rs (MArray' RPure (plus ?_ ?_) ?_)
[ build ] Mismatch between: R1 ?rs ?a and A1 ?rs (MArray' RPure (plus ?_ ?_) ?_).
[ build ] 
[ build ] Data.Array.Mutable:235:7--235:14
[ build ]  231 |   -> (deflt : a)
[ build ]  232 |   -> (1 t : T1 [r])
[ build ]  233 |   -> A1 [] (MArray (m+n) a)
[ build ]  234 | mgrow1 r m dflt t =
[ build ]  235 |   let tgt # t := mgrow r m dflt t
[ build ]              ^^^^^^^
[ build ] 
[ build ] If Builtin.(#): When unifying:
[ build ]     LPair ?a ?b
[ build ] and:
[ build ]     A1 ?rs (MArray' RPure (plus ?_ ?_) ?_)
[ build ] Mismatch between: LPair ?a ?b and A1 ?rs (MArray' RPure (plus ?_ ?_) ?_).
[ build ] 
[ build ] Data.Array.Mutable:235:7--235:14
[ build ]  231 |   -> (deflt : a)
[ build ]  232 |   -> (1 t : T1 [r])
[ build ]  233 |   -> A1 [] (MArray (m+n) a)
[ build ]  234 | mgrow1 r m dflt t =
[ build ]  235 |   let tgt # t := mgrow r m dflt t
[ build ]              ^^^^^^^
[ build ] 
[ build ] If Builtin.DPair.(#): When unifying:
[ build ]     Res ?a ?t
[ build ] and:
[ build ]     A1 ?rs (MArray' RPure (plus ?_ ?_) ?_)
[ build ] Mismatch between: Res ?a ?t and A1 ?rs (MArray' RPure (plus ?_ ?_) ?_).
[ build ] 
[ build ] Data.Array.Mutable:235:7--235:14
[ build ]  231 |   -> (deflt : a)
[ build ]  232 |   -> (1 t : T1 [r])
[ build ]  233 |   -> A1 [] (MArray (m+n) a)
[ build ]  234 | mgrow1 r m dflt t =
[ build ]  235 |   let tgt # t := mgrow r m dflt t
[ build ]              ^^^^^^^
[ build ]
```

**Comment by Matthew-Mosior** [comment]
Maybe I have to replace `A1` with something else as well?

**Comment by stefan-hoeck** [comment]
You need to be on the latest pack collection for this to work. Use `pack switch latest` to update the pack collection.

**Pull request merged**
